### ISSUE TITLE
[Question]: how to configure "application-hadoop.yml" on "no ha hadoop  cluster"

### ISSUE THREAD

**Issue by gitzhou-sin** [cubefs/compass#237]
### Contact Details

zoro361@163.com

### What would you like to ask or discuss?

How do I configure application-hadoop.yml if ha mode is not enabled in my hadoop test cluster
```
hadoop:
  # Configuration dependency for task-application & task-parser modules
  namenodes:
    - nameservices: logs-hdfs               # dfs.nameservices value
      namenodesAddr: [ "machine1.example.com", "machine2.example.com" ]   # dfs.namenode.rpc-address.[nameservice ID].[name node ID] value
      namenodes: ["nn1", "nn2"] # dfs.ha.namenodes.[nameservice ID] value
````
Has anyone tested it? I'd like to have an example
thank you!!!
